---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: istio-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-role
  namespace: istio-system
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-role-binding
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-role
