---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: grafana
  annotations:
    ext.packaging.carvel.dev/fetch-0-secret-name.0: grafana-app-secret
spec:
  serviceAccountName: grafana
  packageRef:
    refName: grafana-app.nasic.gov
    versionSelection:
      constraints: 1.0.0
  values:
    - secretRef:
        name: grafana-app-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-app-secret
stringData:
  values.yml: |
    ---
    path: "/colossus-service-mesh/grafana"
    svc_port: 3000
    target_port: 3000
    app_name: "grafana"
    name_space: "istio-system"
    version: "7.2.1"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: grafana-app-secret
  namespace: kapp-controller-packaging-global
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: add-image-pull-secrets
stringData:
  add-ips.yml: |
    #@ load("@ytt:overlay", "overlay")

    ---
    kind: Secret
    apiVersion: v1
    metadata:
      name: grafana-app-secret
      annotations:
        secretgen.carvel.dev/image-pull-secret: ""
    type: kubernetes.io/dockerconfigjson
    data:
    stringData:
      .dockerconfigjson: ewogImF1dGhzIjogewogImluZGV4LmRvY2tlci5pbyI6IAogIHsKICAgInVzZXJuYW1lIjogInZuYXJheWFuYW4iLAogICAgInBhc3N3b3JkIjogIk1heXVyZXNoMTYhIiwKICAgICJhdXRoIjogImRtNWhjbUY1WVc1aGJqcE5ZWGwxY21WemFERTJJUT09IgogIH0KIH0KfQo=
    #@overlay/match by=overlay.subset({"kind":"Deployment"})
    ---
    spec:
      template:
        spec:
          #@overlay/match missing_ok=True
          imagePullSecrets:
          - name: grafana-app-secret
