# Generate grafana-app-secret secret via
#   kubectl create secret docker-registry k14stest-reg --docker-username=k14stest --docker-password=... --docker-server=index.docker.io -n kapp-controller-packaging-global
apiVersion: v1
kind: Secret
metadata:
  name: grafana-app-secret
  namespace: kapp-controller-packaging-global
  annotations:
   secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/.dockerconfigjson
stringData:
  .dockerconfigjson: ewogImF1dGhzIjogewogImluZGV4LmRvY2tlci5pbyI6IAogIHsKICAgInVzZXJuYW1lIjogInZuYXJheWFuYW4iLAogICAgInBhc3N3b3JkIjogIk1heXVyZXNoMTYhIiwKICAgICJhdXRoIjogImRtNWhjbUY1WVc1aGJqcE5ZWGwxY21WemFERTJJUT09IgogIH0KIH0KfQo=
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: grafana-app-secret
  namespace: kapp-controller-packaging-global
spec:
  toNamespaces:
  - "*"

