---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: grafana-app.nasic.gov
  namespace: kapp-controller-packaging-global
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/vnarayanan/grafana-repo@sha256:bb2411c1a29d4156b902d88fec769d8aebadb108d1e3ffa0e403ebbdc8ef80a7
      secretRef:
        name: grafana-app-secret
